---
# Install and configure Nova
- name: Edit the /etc/nova/nova.conf file and complete the following actions
  ini_file: >
       dest=/etc/nova/nova.conf section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'database',option: 'connection ',value: 'mysql://nova:{{ nova_dbpass }}@{{ controller }}/nova' }
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'nova'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ nova_pass}}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_host',value: '{{ controller }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_userid',value: '{{ rabbit_user }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_password',value: '{{ rabbit_pass }}'}
    - { section: 'DEFAULT',option: 'auth_strategy ',value: 'keystone'}
    - { section: 'DEFAULT',option: 'my_ip ',value: '{{ controller }}'}
    - { section: 'DEFAULT',option: 'rpc_backend',value: 'rabbit'}
    - { section: 'DEFAULT',option: 'network_api_class ',value: 'nova.network.neutronv2.api.API'}
    - { section: 'DEFAULT',option: 'security_group_api ',value: 'neutron'}
    - { section: 'DEFAULT',option: 'linuxnet_interface_driver ',value: 'nova.network.linux_net.NeutronLinuxBridgeInterfaceDriver'}
    - { section: 'DEFAULT',option: 'firewall_driver ',value: 'nova.virt.firewall.NoopFirewallDriver'}
    - { section: 'vnc',option: 'vncserver_listen ',value: '{{ controller }}'}
    - { section: 'vnc',option: 'vncserver_proxyclient_address ',value: '{{ controller }}'}
    - { section: 'glance',option: 'host ',value: '{{ controller }}'}
    - { section: 'oslo_concurrency',option: 'lock_path ',value: '/var/lib/nova/tmp'}
    - { section: 'DEFAULT',option: 'enabled_apis',value: 'osapi_compute,metadata'}
    - { section: 'DEFAULT',option: 'verbose',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: nova_server_config

- name: nova_manage_db_sync
  shell: su -s /bin/sh -c "nova-manage db sync" nova || /bin/true
  tags: nova_server_config
