---
# Install and configure  neutron
- name: Edit the /etc/neutron/neutron.conf  file and complete the following actions
  ini_file: >
       dest=/etc/neutron/neutron.conf  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'database',option: 'connection ',value: 'mysql://neutron:{{ neutron_dbpass }}@{{ controller }}/neutron' }
    - { section: 'DEFAULT',option: 'core_plugin ',value: 'ml2'}
    - { section: 'DEFAULT',option: 'service_plugins ',value: 'router'}
    - { section: 'DEFAULT',option: 'allow_overlapping_ips ',value: 'True'}
    - { section: 'DEFAULT',option: 'rpc_backend ',value: 'rabbit'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_host',value: '{{ controller }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_userid',value: '{{ rabbit_user }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_password',value: '{{ rabbit_pass }}'}
    - { section: 'DEFAULT',option: 'auth_strategy ',value: 'keystone'}
    - { section: 'DEFAULT',option: 'notify_nova_on_port_status_changes ',value: 'True'}
    - { section: 'DEFAULT',option: 'notify_nova_on_port_data_changes ',value: 'True'}
    - { section: 'DEFAULT',option: 'nova_url ',value: 'http://{{ controller }}:8774/v2'}
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'neutron'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ neutron_pass }}'}
    - { section: 'nova',option: 'auth_url ',value: 'http://{{ controller }}:35357'}
    - { section: 'nova',option: 'auth_plugin ',value: 'password'}
    - { section: 'nova',option: 'project_domain_id',value: 'default'}
    - { section: 'nova',option: 'user_domain_id ',value: 'default'}
    - { section: 'nova',option: 'region_name ',value: 'RegionOne'}
    - { section: 'nova',option: 'project_name ',value: 'service'}
    - { section: 'nova',option: 'username ',value: 'nova'}
    - { section: 'nova',option: 'password ',value: '{{ nova_pass }}'}
    - { section: 'oslo_concurrency',option: 'lock_path ',value: '/var/lib/neutron/tmp'}
    - { section: 'DEFAULT',option: 'verbose ',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: neutron_server_config

# Config /etc/neutron/plugins/ml2/ml2_conf.ini
- name: Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file and complete the following actions
  ini_file: >
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'ml2',option: 'type_drivers  ',value: 'flat,vlan,vxlan' }
    - { section: 'ml2',option: 'tenant_network_types ',value: 'vxlan'}
    - { section: 'ml2',option: 'mechanism_drivers ',value: 'linuxbridge,l2population'}
    - { section: 'ml2',option: 'extension_drivers ',value: 'port_security'}
    - { section: 'ml2_type_flat',option: 'flat_networks  ',value: '*'}
    - { section: 'ml2_type_vxlan',option: 'vni_ranges  ',value: '1:1000'}
    - { section: 'securitygroup',option: 'enable_ipset  ',value: 'True'}
  tags: neutron_server_config

- name: symbolic link /etc/neutron/plugin.ini pointing to the ML2 plug-in
  shell: ln -sf /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  tags: neutron_server_config

# Config /etc/nova/nova.conf
- name: Edit the /etc/nova/nova.conf file and complete the following actions
  ini_file: >
     dest=/etc/nova/nova.conf  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'neutron',option: 'url',value: 'http://{{ controller }}:9696' }
    - { section: 'neutron',option: 'auth_url ',value: 'http://{{ controller }}:35357'}
    - { section: 'neutron',option: 'auth_plugin',value: 'password'}
    - { section: 'neutron',option: 'project_domain_id ',value: 'default'}
    - { section: 'neutron',option: 'user_domain_id ',value: 'default'}
    - { section: 'neutron',option: 'region_name ',value: 'RegionOne'}
    - { section: 'neutron',option: 'project_name ',value: 'service'}
    - { section: 'neutron',option: 'username ',value: 'neutron'}
    - { section: 'neutron',option: 'password ',value: '{{ neutron_pass }}'}
    - { section: 'neutron',option: 'service_metadata_proxy  ',value: 'True'}
    - { section: 'neutron',option: 'metadata_proxy_shared_secret ',value: '{{ metadata_secret }}'}
  tags: neutron_server_config
  
- name: neutron_manage_db_sync
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  tags: neutron_server_config