#---
#  - hosts: all
#    roles:
#      - system
#      - zabbix
#      - ntp

#  - hosts: controller_servers
#    roles:
#      - mariadb
#      - mongodb
#      - rabbitmq
#      - keystone
#      - glance
#      - nova_server
#      - neutron_server
#      - dashboard

#  - hosts: compute_servers
#    roles:
#      - nova_compute
#      - neutron_compute
#      - agent