---
# Install and configure neutron
- name: Edit the /etc/neutron/neutron.conf file and complete the following actions
  ini_file: >
    dest=/etc/neutron/neutron.conf  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'DEFAULT',option: 'rpc_backend ',value: 'rabbit'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_host',value: '{{ controller }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_userid',value: '{{ rabbit_user }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_password',value: '{{ rabbit_pass }}'}
    - { section: 'DEFAULT',option: 'auth_strategy ',value: 'keystone'}
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'neutron'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ neutron_pass }}'}
    - { section: 'oslo_concurrency',option: 'lock_path ',value: '/var/lib/neutron/tmp'}
    - { section: 'DEFAULT',option: 'verbose ',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: neutron_compute_config

# Config /etc/neutron/plugins/ml2/ml2_conf.ini 
- name: Edit the /etc/neutron/plugins/ml2/ml2_conf.ini file and complete the following actions
  ini_file: >
    dest=/etc/neutron/plugins/ml2/ml2_conf.ini  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'ml2',option: 'type_drivers  ',value: 'flat,vlan,vxlan' }
    - { section: 'ml2',option: 'tenant_network_types ',value: 'vxlan'}
    - { section: 'ml2',option: 'mechanism_drivers ',value: 'linuxbridge,l2population'}
    - { section: 'ml2',option: 'extension_drivers ',value: 'port_security'}
    - { section: 'ml2_type_flat',option: 'flat_networks  ',value: '*'}
    - { section: 'ml2_type_vxlan',option: 'vni_ranges  ',value: '1:1000'}
    - { section: 'securitygroup',option: 'enable_ipset  ',value: 'True'}
  tags: neutron_compute_config

- name: symbolic link /etc/neutron/plugin.ini pointing to the ML2 plug-in
  shell: ln -sf /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  tags: neutron_compute_config

# Config /etc/neutron/plugins/ml2/linuxbridge_agent.ini
- name: Edit the /etc/neutron/plugins/ml2/linuxbridge_agent.ini file and complete the following actions
  ini_file: >
     dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'linux_bridge',option: 'physical_interface_mappings ',value: 'public:{{ public_interface_name }}' }
    - { section: 'vxlan',option: 'enable_vxlan',value: 'True'}
    - { section: 'vxlan',option: 'local_ip',value: "{{ hostvars[inventory_hostname]['ansible_' + manager_network_interface]['ipv4']['address'] }}"}
    - { section: 'agent',option: 'prevent_arp_spoofing',value: 'True'}
    - { section: 'vxlan',option: 'l2_population ',value: 'True'}
    - { section: 'securitygroup',option: 'enable_security_group ',value: 'True'}
    - { section: 'securitygroup',option: 'firewall_driver',value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver'}
  tags: neutron_compute_config

# Config /etc/nova/nova.conf
- name: Edit the /etc/nova/nova.conf file and complete the following actions
  ini_file: >
     dest=/etc/nova/nova.conf  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'neutron',option: 'url',value: 'http://{{ controller }}:9696' }
    - { section: 'neutron',option: 'auth_url ',value: 'http://{{ controller }}:35357'}
    - { section: 'neutron',option: 'auth_plugin',value: 'password'}
    - { section: 'neutron',option: 'project_domain_id ',value: 'default'}
    - { section: 'neutron',option: 'user_domain_id ',value: 'default'}
    - { section: 'neutron',option: 'region_name ',value: 'RegionOne'}
    - { section: 'neutron',option: 'project_name ',value: 'service'}
    - { section: 'neutron',option: 'username ',value: 'neutron'}
    - { section: 'neutron',option: 'password ',value: '{{ neutron_pass }}'}
  tags: neutron_compute_config